subdir=src/backend/utils/misc
top_builddir=../../../../..
include $(top_builddir)/src/Makefile.global

TARGETS = ps_status bitstream bitmap_compression pg_mkdir_p

include $(top_builddir)/src/backend/mock.mk
