resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    uri: {{gpdb-git-remote}}

- name: centos-coverity
  type: docker-image
  source:
    repository: pivotaldata/centos-coverity
    username: {{docker_username}}
    password: {{docker_password}}

- name: coverity_daily
  type: time
  source:
    location: America/Los_Angeles
    days: [Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
    start: 4:00 AM
    stop: 5:00 AM

- name: libquicklz-centos7
  type: gcs
  source:
    bucket: ((gcs-bucket))
    json_key: ((concourse-gcs-resources-service-account-key)))
    regexp: gp-internal-artifacts/centos7/libquicklz-(1\.5\.0-.*)-1.el7.x86_64.rpm

- name: libquicklz-devel-centos7
  type: gcs
  source:
    bucket: ((gcs-bucket))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: gp-internal-artifacts/centos7/libquicklz-devel-(1\.5\.0-.*)-1.el7.x86_64.rpm

jobs:

- name: coverity_scan
  plan:
  - get: coverity_daily
    trigger: true
  - aggregate:
    - get: gpdb_src
    - get: centos-coverity
    - get: libquicklz-installer
      resource: libquicklz-centos7
    - get: libquicklz-devel-installer
      resource: libquicklz-devel-centos7
  - task: scan_with_coverity
    file: gpdb_src/concourse/tasks/scan_with_coverity.yml
    image: centos-coverity
    params:
      COVERITY_TOKEN: {{coverity_token}}
      COVERITY_EMAIL: {{coverity_email}}
