/*-------------------------------------------------------------------------
 *
 * range_plan.c
 *	  Rangeplan basic functions generated by MS process
 *
 * Copyright (c) 2019-Present, TDSQL
 *
 * IDENTIFICATION
 *	    src/backend/access/kv/range_plan.c
 *
 *-------------------------------------------------------------------------
 */

#include "c.h"
#include "postgres.h"
#include "tdb/range_universal.h"
#include "tdb/range_plan.h"
#include "tdb/range.h"
#include "tdb/route.h"
int RangePlanIdGenerator = 1;
Plan_queue *plan_queue = NULL;

void
initRangePlanHead(RangePlan rangeplan, RangePlanType type)
{
    rangeplan->node_head.type = T_RangePlan;
	rangeplan->plan_id = RangePlanIdGenerator++;
	rangeplan->ms_plan_type = type;
	rangeplan->complete_count = 0;
	MemSet(rangeplan->complete_type, 0, MAXSEGCOUNT);
	MemSet(rangeplan->send_type, 0, MAXSEGCOUNT);
	MemSet(rangeplan->retry_time, 0, MAXSEGCOUNT);
}

/* Request a piece of space in static shared memory to hold all the statistics of the current node. */
void
RangePlanQueueShmemInit(void)
{
	bool found;
	plan_queue = (Plan_queue*)
		ShmemInitStruct("Range Plan Queue", sizeof(Plan_queue), &found);

	if (!IsUnderPostmaster)
	{
		Assert(!found);
		plan_queue->start = 0;
		plan_queue->end = 0;
	}
	else
	{
		Assert(found);
	}
}

Size
RangePlanQueueShmemSize(void)
{
	return sizeof(Plan_queue);
}

char*
TransferSplitPrepareToBuffer(SplitPreparePlan spp, Size* length)
{
	Size range_length;
	char* rangebuffer = TransferRangeDescToBuffer(*spp->split_range, &range_length);

	char* buffer = palloc0(sizeof(SplitPreparePlanDesc) + range_length +
						spp->split_key.len);
	SplitPreparePlan tempsp = (SplitPreparePlan)buffer;
	*tempsp = *spp;
	char* temp = buffer + sizeof(SplitPreparePlanDesc);
	memcpy(temp, spp->split_key.data, spp->split_key.len);
	temp += spp->split_key.len;
	memcpy(temp, rangebuffer, range_length);

	*length = sizeof(SplitPreparePlanDesc) + range_length +
						spp->split_key.len;
	pfree(rangebuffer);
	return buffer;
}

SplitPreparePlan
TransferBufferToSplitPrepare(char* buffer)
{
	SplitPreparePlan tempsp = palloc0(sizeof(SplitPreparePlanDesc));
	*tempsp = *(SplitPreparePlan)buffer;
	//Assert(tempsp->header.ms_plan_type == MS_SPLIT_PLAN);

	char* temp = buffer + sizeof(SplitPreparePlanDesc);

	tempsp->split_key.data = (TupleKey)palloc0(tempsp->split_key.len);
	memcpy(tempsp->split_key.data, temp, tempsp->split_key.len);
	temp += tempsp->split_key.len;

	RangeDesc *range = palloc0(sizeof(RangeDesc));
	*range = TransferBufferToRangeDesc(temp);
	tempsp->split_range = range;
	return tempsp;
}

char*
TransferSplitPlanToBuffer(SplitPlan sp, Size* length)
{
	Size old_range_length, new_range_length;
	char* old_range = TransferRangeDescToBuffer(*sp->old_range, &old_range_length);
	char* new_range = TransferRangeDescToBuffer(*sp->new_range, &new_range_length);
	char* buffer = palloc0(sizeof(SplitPlanDesc) + sizeof(Size) + old_range_length
								 + sizeof(Size) + new_range_length);
	SplitPlan tempsp = (SplitPlan)buffer;
	*tempsp = *sp;
	char* temp = buffer + sizeof(SplitPlanDesc);

	Size* rl = (Size*)temp;
	*rl = old_range_length;
	temp += sizeof(Size);
	memcpy(temp, old_range, old_range_length);
	temp += old_range_length;

	rl = (Size*)temp;
	*rl = new_range_length;
	temp += sizeof(Size);
	memcpy(temp, new_range, new_range_length);
	temp += new_range_length;
	*length = sizeof(SplitPlanDesc) + sizeof(Size) + old_range_length
								 + sizeof(Size) + new_range_length;
	pfree(old_range);
	pfree(new_range);

	return buffer;
}

SplitPlan
TransferBufferToSplitPlan(char* buffer)
{
	SplitPlan sp = palloc0(sizeof(SplitPlanDesc));
	*sp = *(SplitPlan)buffer;

	char* temp = buffer + sizeof(SplitPlanDesc);
	Size rl = *(Size*)temp;
	temp += sizeof(Size);
	RangeDesc *oldrange = palloc0(sizeof(RangeDesc));
	*oldrange = TransferBufferToRangeDesc(temp);
	temp += rl;

	rl = *(Size*)temp;
	temp += sizeof(Size);
	RangeDesc *newrange = palloc0(sizeof(RangeDesc));
	*newrange = TransferBufferToRangeDesc(temp);
	temp += rl;

	sp->old_range = oldrange;
	sp->new_range = newrange;
	return sp;
}

char*
TransferMergePlanToBuffer(MergePlan sp, Size* length)
{
	Size first_range_length, second_range_length;
	char* first_range = TransferRangeDescToBuffer(*sp->first_range, &first_range_length);
	char* second_range = TransferRangeDescToBuffer(*sp->second_range, &second_range_length);
	char* buffer = palloc0(sizeof(MergePlanDesc) + sizeof(Size) + first_range_length
								 + sizeof(Size) + second_range_length);
	MergePlan tempsp = (MergePlan)buffer;
	*tempsp = *sp;
	char* temp = buffer + sizeof(MergePlanDesc);

	Size* rl = (Size*)temp;
	*rl = first_range_length;
	temp += sizeof(Size);
	memcpy(temp, first_range, first_range_length);
	temp += first_range_length;

	rl = (Size*)temp;
	*rl = second_range_length;
	temp += sizeof(Size);
	memcpy(temp, second_range, second_range_length);
	temp += second_range_length;
	*length = sizeof(MergePlanDesc) + sizeof(Size) + first_range_length
								 + sizeof(Size) + second_range_length;
	pfree(first_range);
	pfree(second_range);

	return buffer;
}

MergePlan
TransferBufferToMergePlan(char* buffer)
{
	MergePlan sp = palloc0(sizeof(MergePlanDesc));
	*sp = *(MergePlan)buffer;

	char* temp = buffer + sizeof(MergePlanDesc);
	Size rl = *(Size*)temp;
	temp += sizeof(Size);
	RangeDesc *firstrange = palloc0(sizeof(RangeDesc));
	*firstrange = TransferBufferToRangeDesc(temp);
	temp += rl;

	rl = *(Size*)temp;
	temp += sizeof(Size);
	RangeDesc *secondrange = palloc0(sizeof(RangeDesc));
	*secondrange = TransferBufferToRangeDesc(temp);
	temp += rl;

	sp->first_range = firstrange;
	sp->second_range = secondrange;
	return sp;
}

char*
TransferAddReplicaPlanToBuffer(AddReplicaPlan sp, Size* length)
{
	Size range_length;
	char* range = TransferRangeDescToBuffer(*sp->range, &range_length);
	char* buffer = palloc0(sizeof(AddReplicaPlanDesc) + sizeof(Size) + range_length);
	AddReplicaPlan tempsp = (AddReplicaPlan)buffer;
	*tempsp = *sp;
	char* temp = buffer + sizeof(AddReplicaPlanDesc);

	Size* rl = (Size*)temp;
	*rl = range_length;
	temp += sizeof(Size);
	memcpy(temp, range, range_length);
	temp += range_length;

	*length = sizeof(AddReplicaPlanDesc) + sizeof(Size) + range_length;
	pfree(range);

	return buffer;
}

AddReplicaPlan
TransferBufferToAddReplicaPlanPlan(char* buffer)
{
	AddReplicaPlan sp = palloc0(sizeof(AddReplicaPlanDesc));
	*sp = *(AddReplicaPlan)buffer;

	char* temp = buffer + sizeof(AddReplicaPlanDesc);
	Size rl = *(Size*)temp;
	temp += sizeof(Size);
	RangeDesc *range = palloc0(sizeof(RangeDesc));
	*range = TransferBufferToRangeDesc(temp);
	temp += rl;

	sp->range = range;
	return sp;
}

char*
TransferRemoveReplicaToBuffer(RemoveReplicaPlan sp, Size* length)
{
	Size range_length;
	char* range = TransferRangeDescToBuffer(*sp->range, &range_length);
	char* buffer = palloc0(sizeof(RemoveReplicaPlanDesc) + sizeof(Size) + range_length);
	RemoveReplicaPlan tempsp = (RemoveReplicaPlan)buffer;
	*tempsp = *sp;
	char* temp = buffer + sizeof(RemoveReplicaPlanDesc);

	Size* rl = (Size*)temp;
	*rl = range_length;
	temp += sizeof(Size);
	memcpy(temp, range, range_length);
	temp += range_length;

	*length = sizeof(RemoveReplicaPlanDesc) + sizeof(Size) + range_length;
	pfree(range);

	return buffer;
}

RemoveReplicaPlan
TransferBufferToRemoveReplica(char* buffer)
{
	RemoveReplicaPlan sp = palloc0(sizeof(RemoveReplicaPlanDesc));
	*sp = *(RemoveReplicaPlan)buffer;

	char* temp = buffer + sizeof(RemoveReplicaPlanDesc);
	Size rl = *(Size*)temp;
	temp += sizeof(Size);
	RangeDesc *range = palloc0(sizeof(RangeDesc));
	*range = TransferBufferToRangeDesc(temp);
	temp += rl;

	sp->range = range;
	return sp;
}

char*
TransferRebalancePlanToBuffer(RebalancePlan sp, Size* length)
{
	Size range_length;
	char* range = TransferRangeDescToBuffer(*sp->rebalance_range, &range_length);
	char* buffer = palloc0(sizeof(RebalancePlanDesc) + sizeof(Size) + range_length);
	RebalancePlan tempsp = (RebalancePlan)buffer;
	*tempsp = *sp;
	char* temp = buffer + sizeof(RebalancePlanDesc);

	Size* rl = (Size*)temp;
	*rl = range_length;
	temp += sizeof(Size);
	memcpy(temp, range, range_length);
	temp += range_length;

	*length = sizeof(RebalancePlanDesc) + sizeof(Size) + range_length;
	pfree(range);

	return buffer;
}

RebalancePlan
TransferBufferToRebalancePlan(char* buffer)
{
	RebalancePlan sp = palloc0(sizeof(RebalancePlanDesc));
	*sp = *(RebalancePlan)buffer;

	char* temp = buffer + sizeof(RebalancePlanDesc);
	Size rl = *(Size*)temp;
	temp += sizeof(Size);
	RangeDesc *range = palloc0(sizeof(RangeDesc));
	*range = TransferBufferToRangeDesc(temp);
	temp += rl;

	sp->rebalance_range = range;
	return sp;
}

char*
TransferTransferLeaderPlanToBuffer(TransferLeaderPlan sp, Size* length)
{
	Size range_length;
	char* range = TransferRangeDescToBuffer(*sp->range, &range_length);
	char* buffer = palloc0(sizeof(TransferLeaderPlanDesc) + sizeof(Size) + range_length);
	TransferLeaderPlan tempsp = (TransferLeaderPlan)buffer;
	*tempsp = *sp;
	char* temp = buffer + sizeof(TransferLeaderPlanDesc);

	Size* rl = (Size*)temp;
	*rl = range_length;
	temp += sizeof(Size);
	memcpy(temp, range, range_length);
	temp += range_length;

	*length = sizeof(TransferLeaderPlanDesc) + sizeof(Size) + range_length;
	pfree(range);

	return buffer;
}

TransferLeaderPlan
TransferBufferToTransferLeaderPlan(char* buffer)
{
	TransferLeaderPlan sp = palloc0(sizeof(TransferLeaderPlanDesc));
	*sp = *(TransferLeaderPlan)buffer;

	char* temp = buffer + sizeof(TransferLeaderPlanDesc);
	Size rl = *(Size*)temp;
	temp += sizeof(Size);
	RangeDesc *range = palloc0(sizeof(RangeDesc));
	*range = TransferBufferToRangeDesc(temp);
	temp += rl;

	sp->range = range;
	return sp;
}

/*
 * Because palloc, cannot be used in libpq, the splitplan generated in
 * libpq needs to be replicated and released here.
 */
SplitPlan
TransferSplitPrepareToSplitPlan(SplitPreparePlan lsp)
{
	RangeID id = getMaxRangeID();

	SplitPlan sp = palloc0(sizeof(SplitPlanDesc));
	initRangePlanHead((RangePlan)sp, MS_SPLIT_PLAN);

	sp->targetSegID = lsp->targetSegID;

	/* copy split key */
	TupleKey old_split_key = (TupleKey)palloc0(lsp->split_key.len);
	memcpy((char*)old_split_key, (char*)lsp->split_key.data, lsp->split_key.len);
	TupleKeySlice old_split_key_slice = {old_split_key, lsp->split_key.len};

	//(char*)lsp->split_key.data[lsp->split_key.len - 1]++;
	TupleKey new_split_key = (TupleKey)palloc0(lsp->split_key.len);
	memcpy((char*)new_split_key, (char*)lsp->split_key.data, lsp->split_key.len);
	TupleKeySlice new_split_key_slice = {new_split_key, lsp->split_key.len};
	free(lsp->split_key.data);

	/* copy split range startkey */
	TupleKey start_key = (TupleKey)palloc0(lsp->split_range->startkey.len);
	memcpy((char*)start_key, (char*)lsp->split_range->startkey.data, lsp->split_range->startkey.len);
	TupleKeySlice start_key_slice = {start_key, lsp->split_range->startkey.len};
	free(lsp->split_range->startkey.data);

	/* copy split range endkey */
	TupleKey end_key = (TupleKey)palloc0(lsp->split_range->endkey.len);
	memcpy((char*)end_key, (char*)lsp->split_range->endkey.data, lsp->split_range->endkey.len);
	TupleKeySlice end_key_slice = {end_key, lsp->split_range->endkey.len};
	free(lsp->split_range->endkey.data);

	/* copy split range replica */
	int replica_num = lsp->split_range->replica_num;
	Replica* newreplicas = (Replica*)palloc0(sizeof(Replica) * replica_num);
	Replica* oldreplicas = (Replica*)palloc0(sizeof(Replica) * replica_num);
	for (int i = 0; i < replica_num; i++)
	{
		Replica replica = (Replica)palloc0(sizeof(ReplicaDesc));
		replica->segmentID = lsp->split_range->replica[i]->segmentID;
		replica->replicaID = lsp->split_range->replica[i]->replicaID;
		replica->LeaderReplicaID = lsp->split_range->replica[i]->LeaderReplicaID;
		replica->replica_state = lsp->split_range->replica[i]->replica_state;

		Replica replica1 = (Replica)palloc0(sizeof(ReplicaDesc));
		replica1->segmentID = lsp->split_range->replica[i]->segmentID;
		replica1->replicaID = lsp->split_range->replica[i]->replicaID;
		replica1->LeaderReplicaID = lsp->split_range->replica[i]->LeaderReplicaID;
		replica1->replica_state = lsp->split_range->replica[i]->replica_state;
		newreplicas[i] = replica;
		oldreplicas[i] = replica1;
		free(lsp->split_range->replica[i]);
	}
	free(lsp->split_range->replica);

	RangeDesc* newRange = (RangeDesc*)palloc0(sizeof(RangeDesc));
	*newRange = CreateNewRangeDesc(id, new_split_key_slice,
							end_key_slice, newreplicas, replica_num);
	newRange->version = 0;
	RangeDesc *oldRange = (RangeDesc*)palloc0(sizeof(RangeDesc));
	*oldRange = CreateNewRangeDesc(lsp->split_range->rangeID, start_key_slice,
							old_split_key_slice, oldreplicas, replica_num);
	oldRange->version = lsp->split_range->version + 1;

	sp->old_range = oldRange;
	sp->new_range = newRange;
	free(lsp->split_range);
	free(lsp);
	return sp;
}
