#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/daemon
#
# IDENTIFICATION
#    src/backend/storage/daemon/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/daemon
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = threadpool.o

include $(top_srcdir)/src/backend/common.mk
