#-------------------------------------------------------------------------
#
# Makefile for libtcp
#
# Copyright (c) 1994, Regents of the University of California
#
# src/backend/libtcp
#
#-------------------------------------------------------------------------

subdir = src/backend/libtcp
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global
# override CPPFLAGS := -I$(libpq_srcdir) -I. -I$(srcdir) $(CPPFLAGS)

OBJS = libtcpforcpp.o ltsrpc.pb.o

include $(top_srcdir)/src/backend/common.mk