---
VERSION: 1.0.0.1

TRANSFORMATIONS:

  dblp_input:
    TYPE:     input
    COMMAND:  /bin/bash dblp/input_transform.sh %filename%

  dblp_output:
    TYPE:     output
    COMMAND:  /bin/bash dblp/output_transform.sh %filename%

  mef_input:
    TYPE:     input
    COMMAND:  /bin/bash mef/input_transform.sh %filename%

  rig_input:
    TYPE:     input
    COMMAND:  /bin/bash rig/input_transform.sh %filename%
