#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage
#
# IDENTIFICATION
#    src/backend/tdsqlcontrib/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/tdsqlcontrib
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = storage

include $(top_srcdir)/src/backend/common.mk
