platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
outputs:
  - name: rc_bin_gpdb
run:
  path: gpdb_src/concourse/scripts/gpdb_src_behave_packaging.bash
params:
  GPDB_SRC_TAR_GZ: rc_bin_gpdb/greenplum-db-VERSION_OS-x86_64_src.tar.gz
