platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: bin_gpdb
  - name: binary_swap_gpdb
outputs:
params:
  MAKE_TEST_COMMAND: ""
  BLDWRAP_POSTGRES_CONF_ADDONS: ""
  TEST_OS: ""
  TEST_BINARY_SWAP: ""
  CONFIGURE_FLAGS: ""
run:
  path: gpdb_src/concourse/scripts/ic_gpdb.bash
