---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/ccp
    tag: "7"

inputs:
- name: terraform
- name: ccp_src
- name: cluster_env_files
- name: gpdb_src
- name: bin_gpdb_centos6
- name: sqldump

run:
  path: gpdb_src/concourse/scripts/test_upgrade.bash
  args: [ '-c', '-t', 'bin_gpdb_centos6', '-s', 'sqldump/dump.sql.xz' ]

params:
  DEBUG_UPGRADE: ""
  NUMBER_OF_NODES: 2
