
subdir = src/backend/access/kv/pg_transaction
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

OBJS = normal_engine.o pgtransaction_generate_key.o storage_pg.o

include $(top_srcdir)/src/backend/common.mk
