#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage
#
# IDENTIFICATION
#    src/backend/tdsqlcontrib/storage/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/tdsqlcontrib/storage
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = storage.o

include $(top_srcdir)/src/backend/common.mk
