
subdir = src/backend/access/kv/his_transaction
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

OBJS = storage_his.o his_generate_key.o 

include $(top_srcdir)/src/backend/common.mk
